spring.application.name=restaurant_management_system

server.port=8080

spring.datasource.url=jdbc:sqlserver://ADMIN-PC\\MSSQLSERVER01:1433;databaseName=RestaurantManagementDBa;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456s@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.profiles.active=local

# Mail config (Gmail App Password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khonggidau0@gmail.com
spring.mail.password=mtwbcenhzkgabejr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# PayOS config (thanh toan QR)
payos.client-id=your_payos_client_id
payos.api-key=your_payos_api_key
payos.checksum-key=your_payos_checksum_key

# App URLs
app.frontend-url=http://localhost:3000
